import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import AuthProvider from "@/components/AuthProvider";
import FormInput from "../components/Search";
import ThemeProvider from "@/context/ThemeContext";
import { ReduxProvider } from "@/redux/provider";
import PersistProvider from "@/components/PersistProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Link from "next/link";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            <ThemeProvider>
              <Link href="/cart">
                <ToastContainer
                  position="top-center"
                  theme="dark"
                  autoClose={3000}
                />
              </Link>
              <NavBar />
              <FormInput />
              <div className="min-h-screen">{children}</div>
              <Footer />
            </ThemeProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
